# fly.toml app configuration file generated for lapack-lens on 2026-03-03T18:46:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lapack-lens'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpus = 4
  memory_mb = 1024
